version: '3.7'

services:
  app:
    container_name: app
    image: app_image
    env_file:
      - .env.netflox
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    hostname: app_db
    image: postgres:14.1
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - 6379:6379

volumes:
  app_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: app_main