"""add_view_count_field_for_watch_history

Revision ID: f14e405e52b8
Revises: 95823bb0a058
Create Date: 2023-03-14 17:57:04.426224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f14e405e52b8"
down_revision = "95823bb0a058"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watch_history", sa.Column("view_count", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("watch_history", "view_count")
    # ### end Alembic commands ###
