"""add_movie_unique_constraint

Revision ID: 90703039abc3
Revises: bc3aad78c1b0
Create Date: 2023-03-15 03:36:01.465279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90703039abc3"
down_revision = "bc3aad78c1b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "movie_unique_constraint", "movie", ["title", "original_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("movie_unique_constraint", "movie", type_="unique")
    # ### end Alembic commands ###
