"""add_timezone

Revision ID: 8e99183567c2
Revises: a7f05d87566c
Create Date: 2023-03-14 10:24:25.626237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e99183567c2"
down_revision = "a7f05d87566c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movie", sa.Column("release_year", sa.Integer(), nullable=False))
    op.drop_column("movie", "release_yeare")
    op.add_column(
        "payment_history",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_history", "created_at")
    op.add_column(
        "movie",
        sa.Column("release_yeare", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("movie", "release_year")
    # ### end Alembic commands ###
