"""add_is_activated_field

Revision ID: 32255485b641
Revises: f49c871204f6
Create Date: 2023-03-16 04:23:02.715325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32255485b641"
down_revision = "f49c871204f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_activated", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_activated")
    # ### end Alembic commands ###
