"""add_watch_history_updated_at_field

Revision ID: b964188bc2b0
Revises: 90703039abc3
Create Date: 2023-03-15 12:49:33.658519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b964188bc2b0"
down_revision = "90703039abc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique", "movie_genre", type_="unique")
    op.add_column(
        "watch_history",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("watch_history", "updated_at")
    op.create_unique_constraint("unique", "movie_genre", ["movie_id", "genre_id"])
    # ### end Alembic commands ###
