"""add_email_index

Revision ID: f49c871204f6
Revises: cde6c915a9b7
Create Date: 2023-03-16 04:08:47.559667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f49c871204f6"
down_revision = "cde6c915a9b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("user_email_idx"), "user", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("user_email_idx"), table_name="user")
    # ### end Alembic commands ###
