"""remove_auth_type_and_add_auth_method

Revision ID: 95823bb0a058
Revises: 8e99183567c2
Create Date: 2023-03-14 10:48:45.111847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95823bb0a058"
down_revision = "8e99183567c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("auth_method", sa.String(), server_default="NORMAL", nullable=True),
    )
    op.drop_column("user", "auth_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("auth_type", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("user", "auth_method")
    # ### end Alembic commands ###
