"""add_more_indexes

Revision ID: cde6c915a9b7
Revises: 61cc5dc74f01
Create Date: 2023-03-16 03:27:41.318292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cde6c915a9b7"
down_revision = "61cc5dc74f01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("actor_birthdate_idx"), "actor", ["birthdate"], unique=False)
    op.create_index(op.f("actor_first_name_idx"), "actor", ["first_name"], unique=False)
    op.create_index(op.f("actor_last_name_idx"), "actor", ["last_name"], unique=False)
    op.create_index(
        op.f("movie_release_date_idx"), "movie", ["release_date"], unique=False
    )
    op.create_index(
        op.f("movie_vote_average_idx"), "movie", ["vote_average"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("movie_vote_average_idx"), table_name="movie")
    op.drop_index(op.f("movie_release_date_idx"), table_name="movie")
    op.drop_index(op.f("actor_last_name_idx"), table_name="actor")
    op.drop_index(op.f("actor_first_name_idx"), table_name="actor")
    op.drop_index(op.f("actor_birthdate_idx"), table_name="actor")
    # ### end Alembic commands ###
