name: CI/CD

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and restart docker compose
        run: |
          sudo docker compose build
          sudo docker compose down
          sudo docker compose up -d
